package top.xhbeta.demo.avro;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        System.out.println("Hello world");
    }
}
